  [[main]]
  name = "Main"
  identifier = "main"
  weight = 100
  url = "/de/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/de/post/"

  [[main]]
  name = "Über"
  weight = 300
  identifier = "about"
  url = "/de/about/"

  [[main]]
  name = "Kontakt"
  weight = 400
  identifier = "contact"
  url = "/de/kontakt/"
