  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "CV"
  weight = 300
  identifier = "cv"
  url = "/cv/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Tinkering"
  weight = 400
  identifier = "tinkering"
  url = "/tinkering/"

  [[main]]
  name = "Research"
  weight = 400
  identifier = "research"
  url = "/research/"

  [[main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"
